language: elixir
elixir:
- 1.2.3
otp_release:
- 18.2.1
deploy:
  provider: heroku
  api_key:
    secure: myr07b/j7Kf9Vvje5rGnsA2IP1knxL3LI3hJ8gwB47mIClcSNsHuE47vUu9QivPzyqJPYRZqetkoB3V6RwFtmj1uoPcqnILxMTq7UgOEe+CrZDZgI3io09E/RxOVenB47xOMncPCw2LNKVw81kph2/eQModHOrT++l9Tmf5CB1SLotz/hin7AAktACYbJg7vKbgYPeTB7pmFwE2Jz1/0ZyFqpqlVQ4g0bAAvcIdOxjW3HOg3HF0cuYlTeodVsbl4IUKGujCrxn2Mqk0LShJDkEGrQooqocvrNC3DIG1c22s7/JRM9MKF1VH1OHsnY6X2VJtPb+2QjwSU+zDy7gRaxfst5tNFdbfITW+nMzeb4fI6dCaZSeovdZDF2BVXt2D20ItjbxhwpyF9I7bI4d0S3DD+r3Cp0oEIoGIxeFHq4ixZQ3nFkApMqYkVFmagM9wPkrkXQQAyuH8u3lNaiBcr+Z3nZGOWGWtZTuboczKfcFH37jBrVYwZm6T4KgNlpAuTxZZ7LPRkkrOV3N/0KtZFSFyx5OhqdEsH2vJTs7NJ5nKcY36OPbx3OuUOZMjBtpMcsclPbn5ieesiV06HJyT3W4u6FOAN+V8wwEZSdvWNdKXmyrBgORJJL7llFOcaElUEtlDRyfF5JLAo4PcutzCQVwTf3/mKnByvDXcZRUOvQMA=
  app: scratch-phoenix
  on:
    repo: w0rd-driven/scratch_phoenix
